### ISSUE TITLE
(0.9.11.0) エディタがアクティブ時にグローバルホットキー入力が破棄される

### ISSUE THREAD

**Issue by piyo-gh** [forestail/VaNT-Release#1]
個人的にF8、F9キーにグローバルホットキーを割り当てて外部のクリップボード履歴ツールを呼び出しているのですが、0.9.11.0ではエディタがアクティブな時のみ動作しなくなってしまいました。エディタ以外がアクティブな時は問題なく動作しています。
どうもエディタがアクティブな時に、グローバルホットキーを設定した外部のアプリにキー入力の情報が伝わっていないようです。
VaNT側では定形、ショートカットともにF8、F9には何も割り当てていません。
0.9.10.1では問題ありませんでした。

環境： Windows 10 Pro 20H2 19042.630

**Comment by forestail** [comment]
ファンクションキーを押した際に定型文挿入処理に入り、キー入力をそこで殺していました。
定型文が登録されていないファンクションキーを押した場合は、キー入力を殺さないようにし他アプリに入力を渡すようにします。
次のリリースで対応します。

**Comment by forestail** [comment]
対応したv0.9.11.1をリリースしました。

**Comment by piyo-gh** [comment]
0.9.11.1で動作を確認しました。
ありがとうございました。
