### ISSUE TITLE
ショートカットの設定に関わらずエディタがアクティブ時にCtrl+Qでもウィンドウが閉じる

### ISSUE THREAD

**Issue by piyo-gh** [forestail/VaNT-Release#2]
ウィンドウを閉じるショートカットキーはデフォルトでCtrl+Qが割り当てられていますが、これを[設定/ショートカット]で無効あるいは別のキーを割り当てても、エディタがアクティブな時にはCtrl+Qでもウィンドウが閉じてしまいます。
エディタ以外がアクティブな時は新しく割り当てたキーのみが動作しますが、エディタがアクティブな時には新しく割り当てたキーとCtrl+Qのどちらでもウィンドウが閉じてしまいます。
これは0.9.10.1でも同じでした。

環境： Windows 10 Pro 20H2 19042.630

**Comment by forestail** [comment]
以下が決め打ちで残っていました。
```
if (e.KeyData == (Keys.Control | Keys.Q))
{
    this.Close();
}
```
次のリリースで削除します。

**Comment by forestail** [comment]
対応したv0.9.11.1をリリースしました。

**Comment by piyo-gh** [comment]
0.9.11.1で動作を確認しました。
ありがとうございました。
